# Generated by Django 2.0.1 on 2018-01-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftTitle', models.CharField(default='', max_length=100)),
                ('webAddress', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('image', models.URLField(null=True)),
            ],
        ),
    ]
